---
language: ruby
bundler_args: --without development system_tests
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 1.8.7
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
env:
  - PUPPET_GEM_VERSION="~> 3.8.7" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.6.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
matrix:
  exclude:
